### ISSUE TITLE
Suggest to check if another virtualbox-vm is running when 'make up'

### ISSUE THREAD

**Issue by anencore94** [woohhan/multikube#10]
**What happened**:

vm 을 한 노드에서 여러 개를 띄울 경우 cpu, memory 차지 등의 문제로 머신이 간헐적으로 stuck 이 걸리는 것 같습니다.

**What you expected to happen**:

`make up` command 에서 현재 cpu, memory 사용량과 config.rb 로 들어온 값을 먼저 비교해주는 등의 방식으로 multikube 를 조금 더 안전하게 사용할 수 있도록 해주면 사용하기 편할 것 같습니다.
(multikube 에서 고려해야 하는 부분이 맞는지는 잘은 모르겠습니다.)

**How to reproduce it (as minimally and precisely as possible)**:
1) vagrant 로 vm 을 4개 띄워놓은 후
2) multikube 로 `make up` 

**Environment**:
- Cloud provider or hardware configuration:
  - RAM : 15.5GiB
  - CPU : Intel Core i7-8700 CPU @ 3.20GHz x 12
  - OS : Ubuntu 18.04.4 LTS

**Comment by woohhan** [comment]
kubespray에서 자체적으로 vagrant로 vm을 띄워주기 때문에 vm을 따로 먼저 띄울 필요는 없습니다. vagrant를 쓰지 않고 바로 make up을 했을 때 어떤지 확인 부탁드립니다.

**Comment by anencore94** [comment]
바로 make up 을 했을 때는 문제 없습니다.

제가 언급한 상황은 multikube 와는 별개로 다른 이유로 vm 을 머신에 띄워놓은 상황일 경우에
multikube 로 vm 을 한 번에 여러 개를 동시에 띄우는 상황입니다.

**Comment by woohhan** [comment]
음 그럼 말씀하신대로 VM이 너무 많아져서 생기는 문제인것 같네요. 다만 아주 큰 문제는 아닌 것 같고 (실수로 인터넷 브라우저를 1000개 켜서 컴퓨터가 다운되는 문제와 비슷...) 해결하더라도 Vagrant나 하이퍼바이저 레벨에서 해결되어야 할 것 같습니다.

**Comment by anencore94** [comment]
@woohhan 넵 그럼 이 이슈는 close 하도록 하겠습니다
