### ISSUE TITLE
Make user can change kubernetes version with modifying config.rb or other config file

### ISSUE THREAD

**Issue by anencore94** [woohhan/multikube#12]
현재 multikube 는
multikube/kubespray/inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml 의
kube_version의 값을 참고하여 k8s cluster 를 만들고 있습니다.
(inventory/sample 을 copy 하여 inventory/multikube 를 만들고 있기 때문)

1) 
특정 config 파일에 user 가 원하는 k8s version 을 입력하면 이를 받아서 
multikube/kubespray/inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml  혹은
multikube/kubespray/inventory/multikube/group_vars/k8s-cluster/k8s-cluster.yml 에 값을 변경하여
최종적으로 multikube 가 해당 버전의 k8s cluster 로 생성되도록 변경되면 좋을 것 같습니다.
- 두 방식 중 inventory/sample 을 inventory/multikube 로 copy 후에 inventory/multikube 의 해당 값을 변경하는 방식으로 구현하려 합니다.
- submodule 로 사용하는 릴리즈 버전의 kubespray 에서는 1.15 이상의 version 을 지원가능하다고 써있는 것으로 보입니다만, 테스트는 v1.17.0, v1.16.3 만 해보았습니다.

2)
만약 1. 을 적용하게 된다면,
k8s version 값을 config.rb 에서 다른 parameter 들과 동시에 입력받는게 나을지
아니면 vm 의 instance, name, memory, cpu, subnet, os 등 vm 의 성능과 직접 관련된 config 와
기타 k8s 관련된 config 를 따로 파일로 구분하여 입력받는 것이 나을지도 고민해봐야할 것 같습니다.

*) minikube 에서는 다른 옵션과 마찬가지로 --kubernetes-version 옵션으로 버전을 지정하여 띄울 수 있습니다.
  - 예시) minikube start --kubernetes-version v1.17.0 --vm-driver=kvm2

**Comment by woohhan** [comment]
말씀해주신대로 버전을 지정하는 부분은 꼭 필요할 것 같습니다. config를 어디에 넣어주느냐가 문제인데 config는 되도록이면 한 곳으로 모으고 싶은데, config.rb는 Vagrant의 구현체인 ruby와 연관이 있습니다.

그렇다고 저희가 config.rb에 있는 값을 파싱해서 조작하는 것은 번거로울 것 같네요. 그래서 개인적으로는 kubespray 내에 inventory/multikube 카피를 나중에 하는게 아니라 미리 해놓고 소스코드로 업로드 해두고, inventory에 대한 링크를 만들어서 메인에 두는게 어떨까 생각합니다.

결국 VM 옵션에 대해서는 config.rb와 인벤토리 파일을 양쪽 다 수정해야 하지만 저희가 특별히 구현을 추가하지 않고 kubespray를 그대로 사용할 수 있을 것 같습니다. 어떻게 생각하시나요?

**Comment by anencore94** [comment]
@woohhan
kubespray 내에 inventory/multikube 카피를 미리 해놓고 소스코드로 업로드 해놓는 것은 좋을 것 같습니다.
다만 사용자가 직접 config.rb 와 inventory 파일 내의 yaml 파일을 직접 수정해야 한다면 사용하기 조금 어려울 것 같습니다.

`make up` 시 `make up --k8s-version=v1.17.0 --k8s-cni=weave` 이런 식으로 받을 수  있게 하는 건 어떤가요?
이렇게 할 시에 Makefile 이 많은 option 들을 고려하게 된다면 Makefile 은 점점 복잡해지긴 할 것 같습니다.

**Comment by woohhan** [comment]
> @woohhan
> kubespray 내에 inventory/multikube 카피를 미리 해놓고 소스코드로 업로드 해놓는 것은 좋을 것 같습니다.
> 다만 사용자가 직접 config.rb 와 inventory 파일 내의 yaml 파일을 직접 수정해야 한다면 사용하기 조금 어려울 것 같습니다.
> 
> `make up` 시 `make up --k8s-version=v1.17.0 --k8s-cni=weave` 이런 식으로 받을 수 있게 하는 건 어떤가요?
> 이렇게 할 시에 Makefile 이 많은 option 들을 고려하게 된다면 Makefile 은 점점 복잡해지긴 할 것 같습니다.

구현이 불가능하지는 않지만 저희가 인벤토리의 모든 항목(혹은 필요한 항목)에 대해서 Makefile에 구현을 추가해야 할 것같습니다. kubespray의 업그레이드로 인벤토리 형식이 바뀌거나 하는 등에 대해서도 수정해야 하고 Makefile의 값을 인벤토리 yaml 파일에 적당히 적용도 해줘야 하는데 sed, curl등을 사용하게 될거라 오히려 배보다 배꼽이 크지 않을까 싶습니다.

**Comment by anencore94** [comment]
음 우선 kubespray 가 변경될 수도 있다는 생각을 미처 하지 못했네요.
저도 모든 옵션을 고려해주면 구현하는 사람이 많이 힘들 것 같기는 합니다.
그럼 저희가 소스코드에 넣어놓을 inventory/multikube 내의 yaml 파일을 뭔가 깔끔하게 정리해두고 가이드를 작성해야 하겠네요

**Comment by woohhan** [comment]
> 음 우선 kubespray 가 변경될 수도 있다는 생각을 미처 하지 못했네요.
> 저도 모든 옵션을 고려해주면 구현하는 사람이 많이 힘들 것 같기는 합니다.
> 그럼 저희가 소스코드에 넣어놓을 inventory/multikube 내의 yaml 파일을 뭔가 깔끔하게 정리해두고 가이드를 작성해야 하겠네요
> @woohhan

아니면 반대로 프로젝트 자체의 완성도를 올리기 위해 minikube처럼 기능들을 multikube --k8s-verison=1.16 num_instance=3 이렇게 옮기는 것도 괜찮은 것 같습니다. yaml이나 config.rb에 대해서 정말 사용할만한 아주 한정적인 기능에 대해서만 뚫어주고 관리하는 방법으로요. 조금 성가시기는 한데 minikube를 벤치마킹 한다는 느낌으로 사용법도 비슷하게 가져가는것도 나름 괜찮은 것 같습니다.

**Comment by anencore94** [comment]
넵 그렇게 구현하는 데 드는 시간적 비용과 편의성이 증가되면 이 프로젝트를 사용하는 사람이 많아질지 그리고 처음에 구상하신 이 프로젝트의 목표?존재의 이유?는 무엇인지 등등을 잘 따져봐야할 것 같습니다 :smile:

**Comment by woohhan** [comment]
해당 이슈는 #16 에서 해결 진행하도록 하겠습니다.
