### ISSUE TITLE
set kubectl when deploying multikube

### ISSUE THREAD

**Issue by woohhan** [woohhan/multikube#4]

**Comment by anencore94** [comment]
- 현재 버전의 multikube 의 기본 세팅으로 물리 머신에서 `make up` 을 한 경우, kubectl 을 사용하려면 master node 인 `kub-1` 혹은 `kub-2` 로 ssh 접속 후 `sudo su` 로 root 유저로 바꾼 뒤에야 kubectl 로 cluster 에 접근할 수 있습니다.
  - (kub-1 노드의 /root/.kube/ 디렉토리에 kubeconfig 파일이 있다는 의미)
- 그래서 minikube 처럼 머신에서 바로 사용하려면 이 config 파일을 머신의 ~/.kube/config 에 카피 혹은 add해주는 방법을 사용하거나,
- 아니면 특정 경로에 넣어놓기만 하고 유저가 kubectl config 를 변경하고 싶을 때 변경하도록 변경 방법만 안내해주는 방법이 있을 것 같은데 어떤 방법으로 생각중이신가요?

**Comment by woohhan** [comment]
@anencore94 config를 카피해주는 플래그를 만들고 기본 설정값은 True로 지정하는게 좋지 않을까 생각됩니다. kubespray 자체에 이런 기능을 추가하는것도 (이미 있을지도...) 괜찮을 것 같네요. 받아들여지지 않는다면 여기서 vagrant ssh를 통해 copy해서 추가할 수 있을 것 같습니다.

**Comment by anencore94** [comment]
말씀해주신대로 역시 이미 있네요.([kubespray](https://github.com/kubernetes-sigs/kubespray/blob/master/docs/getting-started.md) 의 마지막 부분)

multikube 의 경우에는 k8s cluster 생성 시에 적용하는 `multikube/kubespray/inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml` 내에 `kubectl_localhost `, `kubeconfig_localhost` 변수가 모두 주석처리되어있는데 이 값들의 default 가 true 인 것인지
이미 true 로 설정한 상황처럼 세팅되어있습니다.

즉, `make up` 하면 multikube/kubespray/inventory/multikube/artifacts 디렉토리 내에 admin.conf 라는 해당 cluster 에 접근 가능한 kubeconfig 파일이 복사되고 이 파일을 바라보고있는 `kubectl.sh` 바이너리도 생성되어 머신(k8s cluster 외부)에서도 이 두 파일 중 하나를 사용하면 정상적으로 접근이 가능합니다.

그럼 multikube 에서는 이 admin.conf 를 copy 해주는 방식으로 사용하는 것이 나을까요?
아니면 Makefile 같은 곳에 kubespray 가 생성해준 `kubectl.sh` 바이너리를 바라보는 kubectl target 을 넣어서 사용하도록 하는 것이 나을까요?

**Comment by woohhan** [comment]
admin.conf를 카피해주는게 사용하기는 편한 것 같은데 multikube로 여러개의 클러스터를 띄울 경우는 어떻게 되는가? 에 대한 문제가 있을 것 같기는 합니다. 하지만 우선은 multikube는 e2e테스트등의 테스트를 위해 사용한다고 가정하면 admin.conf를 ~/.kube/config에 잘 추가해주는것도 괜찮을 것 같습니다. 괜찮으시면 관련해서 작업 진행 부탁드려도 될까요? @anencore94

**Comment by anencore94** [comment]
네 그럼 추후 작업하도록 하겠습니다. @woohhan
