### ISSUE TITLE
need 'virtualenv' package as one of prerequisites

### ISSUE THREAD

**Issue by anencore94** [woohhan/multikube#7]
10 th line in hack.sh, command use virtualenv package.
However, it is not specified in the prerequisites.

Also, even if it fails since my environment doesn't have that package, the next command such as 'vagrant up' starts. However, i think it should return error and break, rather than start 'vagrant up'.

**Comment by woohhan** [comment]
@anencore94 Thanks for reporting this issue. Would you like to fix this issue?
